include:
    - template: Security/Dependency-Scanning.gitlab-ci.yml
    - template: Security/License-Scanning.gitlab-ci.yml
    - template: Security/SAST.gitlab-ci.yml
    - template: Security/Secret-Detection.gitlab-ci.yml
    - project: ens/splunkapps/templates
      file:
      - 'splunkapps-build.gitlab-ci.yml'
      - 'splunkapps-test.gitlab-ci.yml'

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:3.7

stages:
  - build
  - test

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  APP_DIR_NAME: "TA-oversight"
  CUSTOM_LIB_DIR: "TA-oversight"
  SHCLUSTER_APP: "true"
  APP_VERSION: "2.3.5"
  UCC_BUILD: "true"
  SAST_EXCLUDED_ANALYZERS: "semgrep"
  SAST_EXCLUDED_PATHS: spec, test, tests, tmp, venv, .venv  # dont scan build or development tools

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

sanity_check:
  cache: {}
  rules: 
    - when: never
  script:
    - echo "ignore"
