# https://pytest-splunk-addon.readthedocs.io/en/latest/how_to_use.html
version: "3.7"
services:
  splunk:
    build:
      context: .
      dockerfile: Dockerfile-splunk
      args:
        SPLUNK_APP_ID: TA-oversight
        SPLUNK_APP_PACKAGE: output/TA-oversight
        SPLUNK_VERSION: 8.2.2
    ports:
      - "8000"
      - "8088"
      - "8089"
      - "9997"
    environment:
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_START_ARGS=--accept-license